### ISSUE TITLE
Wave Enhance support

### ISSUE THREAD

**Issue by berezovskyi-oleksandr** [Airthings/airthings-ble#49]
**Is your feature request related to a problem? Please describe.**
I just receive the Wave Enhance support and it doesn't seem to be supported by this library

**Describe the solution you'd like**
I'd like to get the Wave Enhance support in this lib to get possibility to enable it in Home Assistant

**Comment by LaStrada** [comment]
This is under development, and will hopefully be released later this month

**Comment by berezovskyi-oleksandr** [comment]
@LaStrada do you have any updates? I'd be happy to get my Wave Enhance sensors integrated

**Comment by samuolis** [comment]
Also waiting for enhanced support. What is the problem to add it? Because it is mostly the same as any other wave device

**Comment by berezovskyi-oleksandr** [comment]
@LaStrada any chance we could help to facilitate the testing and/or development?

**Comment by LaStrada** [comment]
Sorry for the delay. Will try posting what I have during the weekend. What's missing is a check for version when adding it (all devices needs to be updated) + improve code quality + tests.

So it should work now, except for some issues when adding a brand new device (old firmware). Will post it as a custom integration and link it here!

**Comment by guppy** [comment]
Looking forward to this as I'd like to get support added to ESPHome also.

**Comment by LaStrada** [comment]
Again, sorry for the delay. I made some fixes yesterday and will try to publish a beta of the framework, and then make a custom integration that can be imported using HACS or similar later today.

I've fixed the issue with adding devices with old FW, the user is now asked to upgrade using the Airthings app.

Will update here when it's available!

**Comment by LaStrada** [comment]
> Looking forward to this as I'd like to get support added to ESPHome also.

I'm no expert in ESPHome development, but feel free to contact me on Discord (same username) if you, or anyone else, need any help in developing this!

**Comment by berezovskyi-oleksandr** [comment]
> beta of the framework

I tried it and it seems to work. I created a simple executable script to scan BLE devices and then call the lib for the communication
```AirthingsDevice(manufacturer='Airthings AS', hw_version='REV X', sw_version='T-SUB-2.6.2-master+0', model=<AirthingsDeviceType.WAVE_ENHANCE_EU: '3210'>, name='Airthings Tern CO2', identifier='000551', address='B0:D2:78:XX:XX:XX', did_first_sync=True, sensors={'battery': 100, 'lux': 171, 'co2': 688, 'voc': 472, 'humidity': 37.35, 'temperature': 21.53, 'noise': 90, 'pressure': 987.17890625})
```

**Comment by LaStrada** [comment]
A beta can be found here:
https://github.com/LaStrada/HA-Airthings-BLE-beta

Install it as a custom integration using HACS or similar.

Please report bugs either in this thread, create a new issue ticket, or comment on this PR: https://github.com/Airthings/airthings-ble/pull/50

**Comment by samuolis** [comment]
I tested it, it looks like it works quite well. It looks like all of the entities are present, detection was also working so I guess it should be fine. I will work with the data now with this custom integration and will wait for the official update from HA
![Screenshot 2025-01-02 at 11 54 35](https://github.com/user-attachments/assets/41e5e946-d890-480d-919c-9ab2b6720d02)

**Comment by berezovskyi-oleksandr** [comment]
The custom integration works well with both sensors I have. However, I noticed a couple of issues:
1. The battery percentage displayed does not match the value shown in the mobile.
2. One of the devices became unavailable for a period, and when it reconnected, the battery percentage was stuck at 0%, even though other data continued to update correctly.

**Comment by LaStrada** [comment]
Thanks for the feedback! Will look into it. Mine is reporting 100% in HA, but the app is reporting 30%. Definitely something wrong there! 👀

**Comment by LaStrada** [comment]
@berezovskyi-oleksandr That was an easy fix, I forgot to convert from mV to V. 🤦‍♂️ I'll push a fix right away!

Not sure why you got 0%, though. If it persists, I might need to add more logging or debug the raw data in your logs.

**Comment by berezovskyi-oleksandr** [comment]
Perfect, thanks for the fix!

Regarding the 0% issue, it resolved itself after another period of unavailability (likely due to instability in my bluetooth proxy network). I'll monitor this behavior and report it as a separate issue if it happens again.

Aside from these two points, everything works amazingly well! It's great to finally access the CO2 sensor data without relying on the mobile app. I really appreciate your hard work on this!

**Comment by LaStrada** [comment]
I’ve pushed an update to the custom integration:
https://github.com/LaStrada/HA-Airthings-BLE-beta/releases/tag/1.0.0b4

The previous beta release (1.0.0b3) included some fixes for auto-discovery, but I’ve only been able to automatically detect devices on my Mac, not on any of my other HA installations (Intel NUC, RPI4, RPI5). Not sure if this is a bug or an issue with these devices failing to correctly identify the name and/or BLE services of the device.

Has anyone had success with their Home Assistant installation automatically discovering any Wave Enhanced devices?

**Comment by berezovskyi-oleksandr** [comment]
@LaStrada updated to the new custom integration version you just released. Now it shows battery levels other than 100%, but still doesn't match the mobile app. Mobile app reports 89% and 95% in Home Assistant

Regarding auto discovery, worked well with Home Assistant Yellow and ESPHome Bluetooth Proxy. It detected both of my units and added it

**Comment by berezovskyi-oleksandr** [comment]
@LaStrada The integration has been working flawlessly for me since its implementation - great job!

Do you have any updates or plans regarding the merging of this PR and its potential integration into the Home Assistant upstream repository?

**Comment by LaStrada** [comment]
Will make a release this weekend / early next week, and then open a PR to add it into HA. It should hopefully be part of the February release, unless there are any issues 🤞

**Comment by LaStrada** [comment]
> @LaStrada updated to the new custom integration version you just released. Now it shows battery levels other than 100%, but still doesn't match the mobile app. Mobile app reports 89% and 95% in Home Assistant

I see the same. Most of my devices have around 30% battery, and they're reporting 2-10% higher in HA.

Battery is always hard to get 100% the same as from the app. The reason for this is that we have way more code in the cloud to calculate this, so we have tried to make it as simple as possible for now, and this works for all other generations. I will look into this after this has been released and included in HA!

**Comment by berezovskyi-oleksandr** [comment]
@LaStrada hey, do you have any updates regarding the upstreaming process?

**Comment by berezovskyi-oleksandr** [comment]
@LaStrada gentle reminder about the upstreaming process
